import type { CreateWorkspaceInput } from "../domain/workspaces";

export const DEMO_EMAIL = "demo@revenueos.app";
export const DEMO_PASSWORD = "demo1234";

/** The three DEMO businesses. All data is fictitious and clearly labeled DEMO in the UI. */
export const DEMO_WORKSPACES: CreateWorkspaceInput[] = [
  {
    name: "Pequenos Passos",
    industry: "educação infantil",
    description: "Escola de educação infantil com pedagogia afetiva para crianças de 1 a 6 anos.",
    website: "https://pequenospassos.example",
    environment: "DEMO",
    operatingMode: "AUTOPILOT",
    postingSchedule: ["09:00", "18:00"],
    postsPerDay: 2,
    targetPlatforms: ["INSTAGRAM", "TIKTOK", "YOUTUBE"],
    whatsappNumber: "5511900000001",
    color: "#FF7A59",
    audience: {
      targetAudience: "Mães e pais de crianças de 1 a 6 anos, que trabalham fora e buscam uma escola acolhedora",
      problems: ["Não saber se a escola desenvolve o potencial do filho", "Rotina corrida e pouco tempo de qualidade", "Medo de deixar o filho em um lugar sem cuidado de verdade"],
      goals: ["Filho feliz, seguro e aprendendo", "Tranquilidade durante o trabalho", "Acompanhar o desenvolvimento de perto"],
      valueProposition: "Pedagogia afetiva com turmas pequenas e acompanhamento diário pelo app",
      differentiators: ["Turmas de até 12 crianças", "Câmeras ao vivo para os pais", "Alimentação orgânica"],
    },
    brand: {
      primaryColor: "#FF7A59",
      secondaryColor: "#7C6CFF",
      accentColor: "#FFD166",
      backgroundColor: "#17153B",
      textColor: "#FFFFFF",
      fontHeading: "Poppins",
      fontBody: "Inter",
      tone: "acolhedor, próximo e confiável",
      style: "lúdico e moderno",
      voice: "fala com pais como uma coordenadora experiente e carinhosa",
      handle: "pequenospassos",
      keywords: ["educação infantil", "escola", "desenvolvimento infantil", "pais"],
      forbiddenWords: ["barato", "creche depósito"],
      ctaPreferences: ["Agende uma visita", "Chame no WhatsApp"],
    },
    products: [
      {
        name: "Taxa de Matrícula 2026",
        description: "Garante a vaga do seu filho para 2026 com visita guiada e aula experimental inclusa.",
        priceCents: 9900,
        type: "SERVICE",
        benefits: ["Vaga garantida em turmas de até 12 crianças", "Aula experimental inclusa", "Acompanhamento diário pelo app"],
        features: ["Período integral ou meio período", "Câmeras ao vivo", "Alimentação orgânica"],
        faq: [
          { q: "Tem período integral?", a: "Sim! Temos integral (7h às 19h) e meio período, manhã ou tarde." },
          { q: "Posso visitar antes?", a: "Claro! A visita guiada e a aula experimental estão inclusas na matrícula, e você pode agendar a visita antes de pagar." },
          { q: "É seguro?", a: "Sim. Temos câmeras ao vivo para os pais, portaria controlada e equipe com formação em primeiros socorros." },
        ],
        offer: "Matrícula com aula experimental inclusa",
        limitations: ["Vagas limitadas por turma"],
      },
      {
        name: "Colônia de Férias",
        description: "Duas semanas de atividades lúdicas, arte e natureza nas férias.",
        priceCents: 34900,
        type: "SERVICE",
        benefits: ["Atividades ao ar livre", "Arte e música todos os dias"],
        features: ["Das 8h às 17h", "Lanche incluso"],
        faq: [{ q: "Qual a idade?", a: "De 3 a 8 anos." }],
      },
    ],
  },
  {
    name: "Auto Prime",
    industry: "carros seminovos",
    description: "Loja de seminovos revisados com laudo cautelar e garantia.",
    website: "https://autoprime.example",
    environment: "DEMO",
    operatingMode: "AUTOPILOT",
    postingSchedule: ["10:00", "19:00"],
    postsPerDay: 2,
    targetPlatforms: ["INSTAGRAM", "TIKTOK", "YOUTUBE"],
    whatsappNumber: "5511900000002",
    color: "#2F80ED",
    audience: {
      targetAudience: "Motoristas de 25 a 45 anos querendo trocar de carro com segurança",
      problems: ["Medo de comprar carro com problema escondido", "Burocracia e financiamento complicado", "Avaliação injusta do carro usado na troca"],
      goals: ["Carro confiável sem dor de cabeça", "Parcela que cabe no bolso"],
      valueProposition: "Seminovos revisados com laudo cautelar aprovado e garantia de 1 ano",
      differentiators: ["Revisão de 120 itens", "Laudo cautelar em todos os carros", "Avaliação do seu usado na hora"],
    },
    brand: {
      primaryColor: "#2F80ED",
      secondaryColor: "#00C2A8",
      accentColor: "#F2C94C",
      backgroundColor: "#0B1220",
      textColor: "#FFFFFF",
      fontHeading: "Montserrat",
      fontBody: "Inter",
      tone: "confiante, direto e transparente",
      style: "premium e tecnológico",
      voice: "consultor automotivo honesto",
      handle: "autoprime",
      keywords: ["seminovos", "carros", "SUV", "financiamento"],
      forbiddenWords: ["barbada", "sem procedência"],
      ctaPreferences: ["Agende um test-drive", "Chame no WhatsApp"],
    },
    products: [
      {
        name: "Reserva com Sinal",
        description: "Reserve o seminovo escolhido por 72h. O valor do sinal é abatido do preço do carro.",
        priceCents: 9900,
        type: "SERVICE",
        benefits: ["Carro reservado por 72 horas", "Valor abatido na compra", "Test-drive agendado"],
        features: ["Laudo cautelar aprovado", "Garantia de 1 ano", "Financiamento em até 60x"],
        faq: [
          { q: "O sinal é devolvido?", a: "Sim. Se o carro não passar na sua vistoria, devolvemos 100% do sinal." },
          { q: "Aceita troca?", a: "Sim, avaliamos seu usado na hora e ele pode entrar como parte do pagamento." },
          { q: "Tem garantia?", a: "Todos os carros têm garantia de 1 ano para motor e câmbio." },
        ],
        offer: "Taxa zero em 24x para quem reservar esta semana",
      },
      {
        name: "Laudo Cautelar Completo",
        description: "Vistoria completa de qualquer carro que você queira comprar, feita pelos nossos especialistas.",
        priceCents: 14900,
        type: "SERVICE",
        benefits: ["Evite comprar carro com problema", "Relatório em 24h"],
        features: ["Checklist de 120 itens"],
        faq: [{ q: "Serve para carro de outra loja?", a: "Sim, fazemos a vistoria de qualquer veículo." }],
      },
    ],
  },
  {
    name: "OdontoFlow",
    industry: "odontologia",
    description: "Clínica odontológica moderna com atendimento humanizado e agenda online.",
    website: "https://odontoflow.example",
    environment: "DEMO",
    operatingMode: "AUTOPILOT",
    postingSchedule: ["11:00", "20:00"],
    postsPerDay: 2,
    targetPlatforms: ["INSTAGRAM", "TIKTOK", "YOUTUBE"],
    whatsappNumber: "5511900000003",
    color: "#14B8A6",
    audience: {
      targetAudience: "Adultos de 20 a 50 anos que adiam o dentista por medo ou falta de tempo",
      problems: ["Medo de dor no dentista", "Falta de tempo para marcar consulta", "Vergonha do sorriso em fotos"],
      goals: ["Sorriso bonito e saudável", "Atendimento rápido e sem dor"],
      valueProposition: "Odontologia sem dor com agenda online e atendimento no mesmo dia",
      differentiators: ["Anestesia computadorizada", "Agenda online 24h", "Atendimento no mesmo dia"],
    },
    brand: {
      primaryColor: "#14B8A6",
      secondaryColor: "#6366F1",
      accentColor: "#F472B6",
      backgroundColor: "#0B1B24",
      textColor: "#FFFFFF",
      fontHeading: "Sora",
      fontBody: "Inter",
      tone: "calmo, cuidadoso e profissional",
      style: "clean e moderno",
      voice: "dentista que explica tudo com clareza",
      handle: "odontoflow",
      keywords: ["dentista", "sorriso", "clareamento", "odontologia"],
      forbiddenWords: ["indolor garantido", "milagre"],
      ctaPreferences: ["Agende sua avaliação", "Chame no WhatsApp"],
    },
    products: [
      {
        name: "Avaliação + Limpeza",
        description: "Consulta de avaliação completa com limpeza profissional e plano de tratamento.",
        priceCents: 9900,
        type: "APPOINTMENT",
        benefits: ["Diagnóstico completo", "Limpeza profissional na mesma visita", "Plano de tratamento transparente"],
        features: ["Raio-X digital", "Atendimento em até 24h"],
        faq: [
          { q: "Dói?", a: "A limpeza é tranquila. Usamos anestesia computadorizada quando necessário, que reduz muito o desconforto." },
          { q: "Quanto tempo dura?", a: "Cerca de 50 minutos." },
          { q: "Atende no mesmo dia?", a: "Na maioria dos dias sim, conforme a agenda online." },
        ],
        offer: "Avaliação com limpeza por R$ 99",
      },
      {
        name: "Clareamento a Laser",
        description: "Clareamento em consultório com acompanhamento profissional.",
        priceCents: 49000,
        type: "SERVICE",
        benefits: ["Resultado já na primeira sessão", "Acompanhamento profissional"],
        features: ["Sessão de 60 minutos"],
        faq: [{ q: "Precisa de avaliação antes?", a: "Sim, fazemos uma avaliação antes para garantir segurança." }],
        limitations: ["Resultados variam de pessoa para pessoa"],
      },
    ],
  },
];

export const DEMO_FIRST_NAMES = ["Ana", "João", "Mariana", "Pedro", "Juliana", "Lucas", "Camila", "Rafael", "Beatriz", "Gustavo", "Fernanda", "Thiago", "Larissa", "Bruno", "Patrícia", "Felipe", "Aline", "Diego", "Carolina", "Rodrigo", "Letícia", "Marcelo", "Vanessa", "André"];
export const DEMO_LAST_NAMES = ["Silva", "Santos", "Oliveira", "Souza", "Lima", "Pereira", "Costa", "Rodrigues", "Almeida", "Nascimento", "Ferreira", "Carvalho", "Gomes", "Ribeiro"];
